### ISSUE TITLE
RNReactNativeHapticFeedback is not available

### ISSUE THREAD

**Issue by JalalAliyev** [mkuczera/react-native-haptic-feedback#91]
Hey! I want to use haptic vibration once button tap but I have faced weird issue.
When click button I am getting warning and haptic vibration is not working. 

 "react-native": "0.70.1",
 "react-native-haptic-feedback": "^1.14.0",

Usage:
const onHeptic = () => ReactNativeHapticFeedback.trigger('impactMedium', options);

Is this package has any problem?

**Comment by mkuczera** [comment]
Not known at least. Did you run pod install after adding the package?

**Comment by ingvardm** [comment]
Same issue here (after pod install)
"react-native": "0.70.1"
"react-native-haptic-feedback": "2.0.0"

**Comment by Bardiamist** [comment]
Same problem on the old architecture

**Comment by mkuczera** [comment]
Ok, could reproduce. Will fix the issue and involve an example project to avoid further mistakes

**Comment by ingvardm** [comment]
Thanks, @mkuczera, iOS is working, however Android emulator still throws this error.

**Comment by Romick2005** [comment]
Got this build error on iOS:
error Failed to build the app: No package name found. We couldn't parse the namespace from neither your build.gradle[.kts] file at */node_modules/react-native-haptic-feedback/android/build.gradle nor your package in the AndroidManifest at null.

**Comment by ingvardm** [comment]
@mkuczera Everything works now. Thanks and have a productive day!

**Comment by Taher2512** [comment]
Having the same issue again - "RNReactNativeHapticFeedback is not available"

**Comment by hypext1** [comment]
I got this issue when I forgot to
`cd ios; pod install`

**Comment by ayoubechc** [comment]
still getting RNReactNativeHapticFeedback is not available when using 2.0.2, 2.0.1, 2.0.3

**Comment by jordanpy14** [comment]
> 

@ayoubechc where you able to fix it ?

**Comment by ayoubechc** [comment]
> @ayoubechc where you able to fix it ?

I use  version 1.13.0 with react native version :0.66.0, and it work fine

**Comment by EliottPal** [comment]
Same issue here, using the latest version.   

`"react-native-haptic-feedback": "^2.0.3",`

**Comment by lchenfox** [comment]
The same issue on `2.0.3`(`Latest version`).

**Comment by lchenfox** [comment]
I noticed that the issue you said has been fixed in `2.1.0` on conversion: [pull/108](https://github.com/mkuczera/react-native-haptic-feedback/pull/108).  So when will it be published on `2.1.0`?  I really appreciate it if you can publish it soon.

**Comment by farooqalam20996** [comment]
me too, is ther any solution

**Comment by Iuriy-Budnikov** [comment]
I'm still getting an error `RNReactNativeHapticFeedback is not available`

**Comment by juliendevleeschauwer** [comment]
> I'm still getting an error `RNReactNativeHapticFeedback is not available` `2.2.0`

are you rebuild completely the app after install the package ? I rebuild with xcode and the error disapear ;)

**Comment by SathishSaminathan** [comment]
I'm still getting an error RNReactNativeHapticFeedback is not available

**Comment by DieterEOnofre** [comment]
Hello! Im getting a 'WARN' when I try to run: 
`
    if (Platform.OS === 'ios') {
      trigger('impactMedium', optionsButtonFeedback);
    }`
    It says:
     WARN  RNReactNativeHapticFeedback is not available
     Is there a fix for this? Im using version 2.2.0

**Comment by mikhaildegtuarev** [comment]
In the "react-native-haptic-feedback" version: "^2.3.1", this problem is present
